version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "build"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    labels:
      - ""
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
    labels:
      - ""
